// AUTOGENERATED FILE
// This file was generated from Quake.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface QuakeActionDict<T> extends BaseActionDict<T> {
  Digit?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface QuakeSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: QuakeActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: QuakeActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: QuakeActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: QuakeActionDict<T>): this;
}

export interface QuakeGrammar extends Grammar {
  createSemantics(): QuakeSemantics;
  extendSemantics(superSemantics: QuakeSemantics): QuakeSemantics;
}

declare const grammar: QuakeGrammar;
export default grammar;

